version: "3.8"

services:
  db:
    image: postgres:15
    container_name: coupon-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ved1234
      POSTGRES_DB: farmako_coupon_service
    ports:
      - "6543:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net

  app:
    build:
      context: .
    container_name: coupon-service
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net:
